### ISSUE TITLE
Why not center the titleLabel if the subtitle label is not set?

### ISSUE THREAD

**Issue by flypigz** [samvermette/SVPullToRefresh#102]
to make the layout more precise... 
I don't need to subtitle, but the titile label is not center aligned with the arrow, feel strange...

thanks for you wonderful git!

**Comment by samvermette** [comment]
> I don't need to subtitle, but the titile label is not center aligned with the arrow, feel strange...

Do you mean you would have both the arrow and title center aligned, one above another? Or the 2 center aligned as a group?

**Comment by samvermette** [comment]
Ahh did you mean centered vertically? If so, this is fixed with 59d0eb0e94891c14a5a9c67a19001c243bb1b26b

**Comment by flypigz** [comment]
I just verify the commit, work perfectly! Thank you, Sam.
