### ISSUE TITLE
remove infinite scrolling method

### ISSUE THREAD

**Issue by fabiosoft** [samvermette/SVPullToRefresh#112]
i have a not so much infinite feed...i'd like to remove the infiniteScroll callback when a reach the last line.
Example:
now
    __weak ViewController *blockSelf = self;
    if ([self.feed nextLink]) {
        [self.table addInfiniteScrollingWithActionHandler:^{
            [blockSelf loadMore];
        }];
    }

i want to add

}else{

[self.table removeInfiniteScrolling];

}

Thanks

**Comment by viking2009** [comment]
}else{

self.table.showsInfiniteScrolling = NO;

}

**Comment by fabiosoft** [comment]
it works perfect!
thanks! :)
