### ISSUE TITLE
How to show recent cell

### ISSUE THREAD

**Issue by toktak** [samvermette/SVPullToRefresh#115]
Hi Mr.Sam or all who know how to configure the cell ,when im loading the last cell after the loading is done the last cell is get push to the button ..anyone how to push it upward instead of push it down ..Thank in advance  ^w^

**Comment by samvermette** [comment]
Not sure what you mean. You want to add a cell at the top of the tableview or at the bottom? Or are you talking only about the insert animation which you'd like to animate the cell from the top instead of from the bottom?

**Comment by toktak** [comment]
HI Sam,I want it to be like this suppose i have 4(1,2,3,4) row in the beginning and i scroll down till activityindicator is appear .
After the activityindicator finish the process row5 should appear (2,3,4,5) and shift 1 row off to top screen

**Comment by samvermette** [comment]
This is something completely unrelated to SVPullToRefresh. You might have more luck googling something like "animate change UITableView". There must be a hundred questions about this exact topic on StackOverflow. Something like

```
[tableView beginUpdates];
[tableView insertRows...];
[tableView deleteRows...];
// add and remove objects from data source
[tableView endUpdates];
```
