### ISSUE TITLE
Problem with the arrow width in non retina.

### ISSUE THREAD

**Issue by alexito4** [samvermette/SVPullToRefresh#116]
There is some problem with the arrow with in a non retina screen.
If you pull down to refresh multiple times the width will increment.

The problem only occurs when the view has a title. If you comment the line that set the title to @"" in the demo project you will se that:

![Captura de pantalla 2013-03-25 a la s 09 14 59](https://f.cloud.github.com/assets/750912/297032/8c024f02-9524-11e2-88a7-ef155ff067ca.png)

**Comment by samvermette** [comment]
Thanks for reporting this.
