### ISSUE TITLE
wrong arrow size on non-Retina Simulator (not tested on device)

### ISSUE THREAD

**Issue by viking2009** [samvermette/SVPullToRefresh#118]
on non-Retina Simulator (iOS 6.1) arrow width grows

-[SVPullToRefreshView layoutSubviews] [Line 256] self.arrow.frame = {{110, 6}, {23, 48}}
-[SVPullToRefreshView layoutSubviews] [Line 256] self.arrow.frame = {{109, 6}, {25, 48}}
....
-[SVPullToRefreshView layoutSubviews] [Line 256] self.arrow.frame = {{83, 6}, {38, 48}}

issue fixes with next code

```
   CGFloat arrowX = (self.bounds.size.width / 2) - (totalMaxWidth / 2) + (leftViewWidth - self.arrow.bounds.size.width) / 2;
    arrowX = floorf(arrowX);
    self.arrow.frame = CGRectIntegral(CGRectMake(arrowX,(self.bounds.size.height / 2) - (self.arrow.bounds.size.height / 2),self.arrow.bounds.size.width,self.arrow.bounds.size.height));
```

-[SVPullToRefreshView layoutSubviews] [Line 257] self.arrow.frame = {{91, 6}, {22, 48}}
-[SVPullToRefreshView layoutSubviews] [Line 257] self.arrow.frame = {{91, 6}, {22, 48}}
...
-[SVPullToRefreshView layoutSubviews] [Line 257] self.arrow.frame = {{91, 6}, {22, 48}}

**Comment by samvermette** [comment]
See #116. Are you using the latest version?

**Comment by viking2009** [comment]
I've updated to last version, thanks
