### ISSUE TITLE
Issue with color customization

### ISSUE THREAD

**Issue by vangras** [samvermette/SVPullToRefresh#122]
Hi!

first of all thanks for sharing this wonderful component!

I may be doing something wrong, but it seems that changing colors han no effect, neither in my project nor in the demo. I added the following to the demo SVViewController viewDidLoad method: 

[...]
    __weak SVViewController *weakSelf = self;

```
self.tableView.pullToRefreshView.arrowColor = [UIColor whiteColor];
self.tableView.pullToRefreshView.textColor = [UIColor whiteColor];
self.tableView.pullToRefreshView.activityIndicatorViewStyle = UIActivityIndicatorViewStyleWhite;
self.tableView.infiniteScrollingView.activityIndicatorViewStyle = UIActivityIndicatorViewStyleWhite;


// setup pull-to-refresh
[self.tableView addPullToRefreshWithActionHandler:^{
    [weakSelf insertRowAtTop];
}];
```

[...]

No change neither in the arrow or text colors nor activityIndicatorView.

**Comment by samvermette** [comment]
Can you try setting up the colors **after** doing the `addPullToRefreshWithActionHandler:` call see if that fixes it?

**Comment by vangras** [comment]
yep it works! Thanks!

**Comment by seandeng** [comment]
oh....  !!!!   thanks very much .  you should tell us when we use setTitle setCustomer after doing the add addPullToRefreshWithActionHandler
