### ISSUE TITLE
0.4.2

### ISSUE THREAD

**Issue by dennisreimann** [samvermette/SVPullToRefresh#136]
Hey Sam, can we have a new release with the recent fixes?

**Comment by hunter-eric** [comment]
+1

**Comment by JRG-Developer** [comment]
+1 Agreed. There's some nice pull requests pending, and it'd be great to see these in the main repo.

**Comment by AdiletAbylov** [comment]
+1

**Comment by michelzanini** [comment]
+1 to merge some pull requests and release new version

**Comment by tomasikp** [comment]
@samvermette +1

**Comment by JavaCS** [comment]
+1

**Comment by raphaeloliveira** [comment]
+1
