### ISSUE TITLE
BridgeSupport is not parsing files properly

### ISSUE THREAD

**Issue by brandonarbini** [samvermette/SVPullToRefresh#15]
Hi. So, I'm pretty new to iOS development and I'm actually using RubyMotion. I really like this implementation of "pull to refresh" and I'd like to use it in my RubyMotion project via cocoapods (and motion-cocoapods). However, the `.bridgesupport` file is missing the UIScrollView extensions. I know that this is probably an issue with `gen_bridge_metadata`, but I thought I'd see if you are familiar with MacRuby/RubyMotion and what it does to get Obj-C projects working.

Here's the file:

``` xml
<?xml version='1.0'?>
<signatures version='1.0'>
<class name='SVPullToRefresh'>
<method selector='activityIndicatorViewStyle'>
<retval declared_type='int' type='i'/>
</method>
<method selector='arrowColor'>
<retval declared_type='int*' type='^i'/>
</method>
<method selector='setActivityIndicatorViewStyle:'>
<arg name='activityIndicatorViewStyle' declared_type='int' type='i' index='0'/>
<retval declared_type='void' type='v'/>
</method>
<method selector='setArrowColor:'>
<arg name='arrowColor' declared_type='int*' type='^i' index='0'/>
<retval declared_type='void' type='v'/>
</method>
<method selector='setTextColor:'>
<arg name='textColor' declared_type='int*' type='^i' index='0'/>
<retval declared_type='void' type='v'/>
</method>
<method selector='stopAnimating'>
<retval declared_type='void' type='v'/>
</method>
<method selector='textColor'>
<retval declared_type='int*' type='^i'/>
</method>
</class>
</signatures>
```

Any assistance would be much appreciated.

**Comment by samvermette** [comment]
I am completely unfamiliar with MacRuby/RubyMotion. If you ask me, iOS development should be done in Obj-C in Xcode :)

**Comment by brandonarbini** [comment]
Ha! Fair enough. Thanks for the reply. :)

## 

Brandon Arbini
