### ISSUE TITLE
IOS7 and UINavigationController

### ISSUE THREAD

**Issue by damooooooooooh** [samvermette/SVPullToRefresh#156]
When ScrollViewDidScroll event fires the tableview moves up under the UINavigationBar.

**Comment by Bubcho** [comment]
@diehardguy I fixed this by telling the view controller to stop adjusting my scroll view's insets automatically and setting them manually, like this:

if ([self respondsToSelector:@selector(automaticallyAdjustsScrollViewInsets)]) {
        self.automaticallyAdjustsScrollViewInsets = NO;

```
    UIEdgeInsets insets = self.tableView.contentInset;
    insets.top = self.navigationController.navigationBar.bounds.size.height + 
                                       [UIApplication sharedApplication].statusBarFrame.size.height;
    self.tableView.contentInset = insets;
    self.tableView.scrollIndicatorInsets = insets;
}
```

**Comment by damooooooooooh** [comment]
@Bubcho many thanks.  I tried this by adding it to my UITableviewController super class init and viewdidload methods and now when the tableview is populated it is initially appearing under the navigation bar.  Before adding this fix, the tableview only moved up when the tableview was scrolled.  Can you advise where I need to put this? Thanks!

**Comment by damooooooooooh** [comment]
Adding 

[self.tableView addPullToRefreshWithActionHandler:^{

in viewdidappear fixed the issue for me.

**Comment by cocoajin** [comment]
thanks 
just like this

```
    /**
     *  下拉刷新 增加一个；
     */

    if ([self respondsToSelector:@selector(automaticallyAdjustsScrollViewInsets)]) {
        self.automaticallyAdjustsScrollViewInsets = NO;

        UIEdgeInsets insets = self.tableView.contentInset;
        insets.top = self.navigationController.navigationBar.bounds.size.height +
        [UIApplication sharedApplication].statusBarFrame.size.height;
        self.tableView.contentInset = insets;
        self.tableView.scrollIndicatorInsets = insets;
    }

    __block RootViewController *bSelf = self;

    [self.tableView addPullToRefreshWithActionHandler:^{

        [bSelf addRows];
    }];


    /**
     *  拉到最后 加载更多，增加一个；
     */
    [self.tableView addInfiniteScrollingWithActionHandler:^{
        [bSelf addMoreRow];
    }];

```

**Comment by kazarus** [comment]
thanks, got it.

**Comment by limsungmook** [comment]
@cocoajin It works. Thanks.

**Comment by zvving** [comment]
In iOS7 can reappear it also. I think it's a bug. 

If add `addPullToRefreshWithActionHandler` in `viewdidload` ( Subclass UITableViewController), then SVPullToRefresh load a wrong `originalTopInset` value.

cc @samvermette
