### ISSUE TITLE
Observer leak when SVInfiniteScrollingView was hidden

### ISSUE THREAD

**Issue by enefry** [samvermette/SVPullToRefresh#164]
UIScrollView+SVInfiniteScrolling.m
- (void)willMoveToSuperview:(UIView *)newSuperview {
  if (self.superview && newSuperview == nil) {
      UIScrollView *scrollView = (UIScrollView *)self.superview;
      if (scrollView.showsInfiniteScrolling) {
        if (self.isObserving) {
          [scrollView removeObserver:self forKeyPath:@"contentOffset"];
          [scrollView removeObserver:self forKeyPath:@"contentSize"];
          self.isObserving = NO;
        }
      }
  }
  }

when SVInfiniteScrollingView was dealloc and scrollview dealloc  . SVInfiniteScrollingView never remove Observer . 
I try to delete  lines 
if (scrollView.showsInfiniteScrolling) { }
It work fine

And I have an other issue was  #160  Crash while addInfiniteScrollingWithActionHandler  .
I am not sure it is not caused by

**Comment by captain-black** [comment]
I figured it out!
__
if (!self.infiniteScrollingView.isObserving) {
            [self addObserver:self.infiniteScrollingView forKeyPath:@"contentOffset" options:NSKeyValueObservingOptionNew context:nil];
            [self addObserver:self.infiniteScrollingView forKeyPath:@"contentSize" options:NSKeyValueObservingOptionNew context:nil];
            [self.infiniteScrollingView setScrollViewContentInsetForInfiniteScrolling];
            self.infiniteScrollingView.isObserving = YES;
}
__
In my case, UITableView
when call  [self.infiniteScrollingView setScrollViewContentInsetForInfiniteScrolling]; If contentInset did change, It cause UITableView updateContent and call dataSource, If I set self.showsInfiniteScrolling = YES, It will addObserver again, becase self.infiniteScrollingView.isObserving value is still NO.

fixed it:
__
if (!self.infiniteScrollingView.isObserving) {
            self.infiniteScrollingView.isObserving = YES;
            [self addObserver:self.infiniteScrollingView forKeyPath:@"contentOffset" options:NSKeyValueObservingOptionNew context:nil];
            [self addObserver:self.infiniteScrollingView forKeyPath:@"contentSize" options:NSKeyValueObservingOptionNew context:nil];
            [self.infiniteScrollingView setScrollViewContentInsetForInfiniteScrolling];
            //self.infiniteScrollingView.isObserving = YES;
}
__
