### ISSUE TITLE
InfiniteScroll - ContentOffset of UIScrollView does not return to normal when changing to a "stopped" state

### ISSUE THREAD

**Issue by siburbOther** [samvermette/SVPullToRefresh#170]
I've implemented SVInfiniteScrolling on a UITableView in an iOS7 app.

When I pull up on the table, the UIActivityIndicator shows correctly, and then disappears when the update request has completed, but the UITableView doesn't return to its original offset, the contentOffset continues to show the space where the UIActivityIndicator was.

This would probably not be an issue if any new data was loaded (new rows added at the bottom of the UITableView), but when no new data is found (and particularly on a paged UIScrollView as in my case) it looks very odd.

I'm not using any custom views for the infinite scrolling - just the standard implementation.

Thanks, and Happy New Year!

**Comment by tuchangwei** [comment]
After the data loaded, you should call the following methods:

``` Object-c
[self.tableView.infiniteScrollingView stopAnimating];//if not, the loading more block will not be called next time.
self.tableView.showsInfiniteScrolling = NO;//return to normal.
```
