### ISSUE TITLE
KVO Error on Table View dealloc

### ISSUE THREAD

**Issue by pwightman** [samvermette/SVPullToRefresh#19]
I'm getting the following error message when a table view I have attached pullToRefresh to is deallocated:

```
An instance 0x882e800 of class UITableView was deallocated while key value observers were still registered with it. Observation info was leaked, and may even become mistakenly attached to some other object. Set a breakpoint on NSKVODeallocateBreak to stop here in the debugger. Here's the current observation info:
<NSKeyValueObservationInfo 0x8156ef0> (
<NSKeyValueObservance 0x8156e30: Observer: 0x8154b70, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x82419b0>
<NSKeyValueObservance 0x8156eb0: Observer: 0x8154b70, Key path: frame, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x8247fc0>
)
```

Am I doing something wrong? Is there a conventional way to break the KV observance I'm not aware of?

The only code I'm running related to pull-to-refresh is:

```
[self.tableView addPullToRefreshWithActionHandler:^{
    [tempManager updateQueue];
}];
```

and

```
[self.tableView.pullToRefreshView stopAnimating];
```

Thanks.

**Comment by asmallteapot** [comment]
If you’re observing a value on the table view, it should be removed before the table view is deallocated. That would usually be in the view controller’s `-dealloc` method. Where are you removing it now?

**Comment by pwightman** [comment]
I'm not removing them, I suppose that's my question. I never added observers myself, `addPullToRefreshWithActionHandler` is adding them (or so says the README?), must I manually remove them? The README didn't mention anything about having to manually remove pull-to-refresh functionality so I wondered if 1) I'm doing it wrong or 2) what is the conventional way others using this library have manually removed them? Can it be encapsulated in a method like `[self.tableView removePullToRefresh]` that I can call inside `viewDidUnload`?

Thanks for any help and patience, I'm not too familiar with KVO and might be over looking something very basic.

**Comment by pwightman** [comment]
Hmmm... So looking at SVPullToRefresh.m/.h, it removes them itself inside its own `dealloc` method, which means my view controller is not deallocating the `pullToRefreshView` property of the table view before itself is being deallocated, so that must be my problem. So yeah, I think I'm just doing my memory management wrong. I'll investigate the issue, post how I fixed it here and close it (unless others have any insights they care to share).

Thanks!

**Comment by pwightman** [comment]
Pulling the latest version of SVPullToRefresh seems to have fixed it, must have just been a bug in an older version.

Cheers.

**Comment by samvermette** [comment]
@pwightman yes, that was a bug with a previous version of SVProgressHUD. Glad that you got it fixed.

**Comment by nishan-guiddit** [comment]
@pwightman I'm having the same issue. Pull TO Refresh code is creating problems. Can I have the updated code for the same ?

**Comment by bhavinopenxcell** [comment]
I have latest version of SVPullToRefresh and i successfully run it in iOS 8.4 but i need to make iOS 9 compatible app. For that i update my Xcode to 7.0 and iOS 9 SDK after update i facing this issue again. I don't know what i'm doing wrong. Please guide on this.
