### ISSUE TITLE
add Infinite scrolling (SVPullToRefreshPosition)position method please.

### ISSUE THREAD

**Issue by cooler333** [samvermette/SVPullToRefresh#202]
- (void)addInfiniteScrollingWithActionHandler:(void (^)(void))actionHandler position:(SVPullToRefreshPosition)position;

like
- (void)addPullToRefreshWithActionHandler:(void (^)(void))actionHandler position:(SVPullToRefreshPosition)position;

**Comment by d4r1091** [comment]
try this: https://github.com/d4r1091/SVPullToRefresh
in this repo there is a branch called "dev". I started an implementation of this requested method and seems work!
try if you want.
thanks

**Comment by fresh83** [comment]
not sure what you mean by position....how about just letting us choose to start the load more about 500 px highter than before its needed?
