### ISSUE TITLE
present view controller with completion block issues

### ISSUE THREAD

**Issue by Hackmodford** [samvermette/SVPullToRefresh#21]
I'm trying to present a modal view controller after the pull to refresh. I can present it fine but it doesn't animate. Is there something I should be aware of when presenting a view controller from within a block?

**Comment by samvermette** [comment]
The following code seems to be working fine here:

```
[self.tableView addPullToRefreshWithActionHandler:^{
    dispatch_async(dispatch_get_main_queue(), ^{
        SVViewController *vc = [[SVViewController alloc] initWithNibName:@"SVViewController" bundle:[NSBundle mainBundle]];
        [self presentModalViewController:vc animated:YES];
    });
}];
```

The modal view is sliding in with an animation as expected. Maybe there's something wrong somewhere else in your code?

**Comment by Hackmodford** [comment]
That worked great.
