### ISSUE TITLE
UICollectionView not showing pull to refresh

### ISSUE THREAD

**Issue by hemangshah** [samvermette/SVPullToRefresh#229]
UICollectionView not showing pull to refresh if content size height is lesser than the collection view height. What to do with this?

**Comment by chrise86** [comment]
I think I'm having the same problem, in an empty UICollectionView, the pull to refresh controls do not work. Did you manage to solve it?

**Comment by hemangshah** [comment]
@chrise86, The good news is that its working for me now :)

Please try with

CollectionView.alwaysBounceVertical = YES;

**Comment by chrise86** [comment]
Seems to do the trick!

**Comment by chrise86** [comment]
Actually, `collectionView.alwaysBounceVertical = YES;` did not fix it... any other ideas?

**Comment by chinabshah** [comment]
Not working for me either!

**Comment by easonoutlook** [comment]
add this code to viewDidLoad resolved this!

if ([self respondsToSelector:@selector(edgesForExtendedLayout)]){
        self.edgesForExtendedLayout = UIRectEdgeNone;
    }

**Comment by caojianhua** [comment]
@hemangshah thx, its working for me
