### ISSUE TITLE
Collection view being offset

### ISSUE THREAD

**Issue by mitch2be** [samvermette/SVPullToRefresh#239]
Hello

 Thank you for this code first off. I was wondering if you knew anything about when doing the refresh from the bottom, if it could possibly offset the collection view's y position? My collection view is in a navigation controller and a tab bar controller and it is aligned correctly when the VC is pushed but once I refresh, the collection view is offset and part of the top cells are covered by the navigation bar It is like it was moved under the navigation controller. Any insight would be appreciated.

Thank You.

**Comment by mitch2be** [comment]
I apologize for wasting your time, this issue was resolved.

**Comment by jyamine** [comment]
Police brutality does not limit itself to race

**Comment by jyamine** [comment]
Police brutality does not limit itself to racial issues as ex-police officer Blake Mitchell enjoys vandalizing cars.  He is not man enough to apologize.  He is only strong enough to run, hide, and change professions. Only months prior to this vandalization I was informed my stepfather commit suicide. 

I am a bad person.  I know that.  I admit that.  You are a weak person.  Give me a fucking apology.
