### ISSUE TITLE
addInfiniteScrollingWithActionHandler causes the collectionView or tableView to blink

### ISSUE THREAD

**Issue by marcelosalloum** [samvermette/SVPullToRefresh#242]
Hey guys,

not sure if it has ever happened to you but when I add the infiniteScrolling to my CollectionView or tableView it blinks. Always happens to collectionViews but not always to tableView.

Does anyone also experiences this kind of thing?

Thanks

**Comment by fuacici** [comment]
It happend to me as well, I think it's the contentInset cause the problem.

**Comment by marcelosalloum** [comment]
Not sure what was the cause, but I managed to fix the problem by dispatching call of reloadData to the main queue:

```
dispatch_async(dispatch_get_main_queue(), ^{
    [self.collectionView reloadData];
});
```

**Comment by fuacici** [comment]
My issue is caused by estimatedRowHeight.should not set it then.
