### ISSUE TITLE
SVPullToRefresh cause a crash

### ISSUE THREAD

**Issue by FrankCYQ** [samvermette/SVPullToRefresh#247]
[(UITableView/UIScrollView)WrapperView _systemGestureStateChanged:]: message sent to deallocated instance xxx

i add the SVPullToRefresh's files to my project , then i (present/push) a tableviewController or have anyone subview of uiscrollview's UIViewController (ctA) ,ctA don't need use  SVPullToRefresh stuff , but when i (dismiss/pop) ctA ,  this moment trigger ctA's dealloc method, then it cause the subview of uiscrollview dealloc,  after that ,ur application will crash when u touch anywhere on the screen, the error information is  [UITableView/UIScrollView WrapperView _systemGestureStateChanged:]: message sent to deallocated instance xxx, i have no idea what to do ,i do nothing with the original files of SVPullToRefresh, i tested this situation using swift and object-c , just got the same error.  
Is there anyone could help me to solve this problem, i'm waiting for ur help, thanks

**Comment by FrankCYQ** [comment]
i made a mistake, wrote the dealloc method at the "UIScrollView+SVInfiniteScrolling.m"  and "UIScrollView+SVPullToRefresh.m" ,then i got the crash info . maybe we should never do this at a category implement file

**Comment by hynever** [comment]
thankss, i met the same problem too,but why?

**Comment by FrankCYQ** [comment]
when i have time ,i'll find the answer
