### ISSUE TITLE
cocoapods repo

### ISSUE THREAD

**Issue by felipesabino** [samvermette/SVPullToRefresh#25]
any plans on adding a pod spec file and submitting it to the cocoapods repo?

http://cocoapods.org/

**Comment by brandonarbini** [comment]
It's already there: https://github.com/CocoaPods/Specs/tree/master/SVPullToRefresh.

**Comment by samvermette** [comment]
Just tagged the latest commit with 0.2, if someone can push that to the cocoapods repo.
