### ISSUE TITLE
Fork and continue this project to give maintenance

### ISSUE THREAD

**Issue by CavalcanteLeo** [samvermette/SVPullToRefresh#282]
is visibly clear that the project **is abandoned**, what do you guys think of forking the project and continue in another repository to give maintenance. 

There are: 
- 54 Pull requests
- 93 opened issues

and the last commit was on 26 Sep 2013 (almost 4 years ago)

**Comment by arielpollack** [comment]
+1

**Comment by cbowns** [comment]
If someone wants to be a project maintainer, we can have Sam add them to the project as a contributor, so any updates we make go into his repo (and thus, downstream clients tracking `master` and the project's tags) will pick them up, rather than needing to target a new fork.

**Comment by asxasxasx** [comment]
Here is my copy of repo with most important updates and bugfixes. Feel free to use https://github.com/asxasxasx/SVPullToRefresh

**Comment by LawrenceHan** [comment]
https://github.com/LawrenceHan/SVPullToRefresh
