### ISSUE TITLE
Hi guys please go to my forked repo to have new feature/bug fixed.

### ISSUE THREAD

**Issue by LawrenceHan** [samvermette/SVPullToRefresh#299]
https://github.com/LawrenceHan/SVPullToRefresh

**Comment by ErAshu** [comment]
does it works for collectionview??

**Comment by LawrenceHan** [comment]
@ErAshu Yes it does, but you may need to set `alwaysBounceVertical` or `alwaysBounceHorizontal` to YES manually.

**Comment by kieuquangloc** [comment]
Hi @LawrenceHan , could you enable "issues" tab in your fork setting?, I think some people want to create issue to discuss in your fork like me :)

<img width="616" alt="screen shot 2018-09-11 at 2 57 41 pm" src="https://user-images.githubusercontent.com/8148640/45346377-3c591c80-b5d3-11e8-9280-1efea3dac275.png">

**Comment by LawrenceHan** [comment]
@kieuquangloc147 Done
