### ISSUE TITLE
default arrowColor not working in 4.3

### ISSUE THREAD

**Issue by travisweerts** [samvermette/SVPullToRefresh#34]
For some reason, when running 4.3, if you set the arrowColor to black or gray, the arrow doesn't show up. In 5.0, its fine.

**Comment by pcasaretto** [comment]
What color worked for you?

**Comment by travisweerts** [comment]
Pretty much every color but black or gray? I tried red, purple, yellow, blue... etc. I also set the background color of the arrow to a few different colors just to see if I could see the shape of the arrow, but I couldn't... so I set it back to clear.

**Comment by pcasaretto** [comment]
Did you use the arrowColor accessor? I had to hard code the orange color on drawRect to get it working.

**Comment by travisweerts** [comment]
yeah, I used the arrowColor accessor

**Comment by samvermette** [comment]
@travisweerts @pcasaretto I believe this has been fixed with @smorel's pull request that I just merged. Feel free to reopen the issue if it that isn't the case.
