### ISSUE TITLE
not supporting infinite scrolling for UIScrollView

### ISSUE THREAD

**Issue by hhkim** [samvermette/SVPullToRefresh#38]
You use the footer view of UITableView for infinite scrolling.
Is there some reason why you are not supporting UIScrollView?
I hope to use SVPullToRefresh with using grid control like [AQGridView](https://github.com/AlanQuatermain/AQGridView/).

**Comment by guoxj** [comment]
i  alse use AQGridView previously,but i found some bug that hard to fix. then i changed to KKGridView.

and i have make a quick and dirty fix that may also works for you.

download link:  https://www.box.com/s/30dd2a61b08d13b296c3

**Comment by samvermette** [comment]
@hhkim using UITableView's footer view was a lot less work than dealing manually with the content sizes and offsets to always make sure the infinite scrolling view gets placed right. Ideally I'd like the infinite scrolling to work with UIScrollView, I just haven't got the time yet to make the change. Will leave this issue open until someone (myself included) submits a pull request that adds support for this.

**Comment by samvermette** [comment]
The refactor I just pushed now adds the infinite scrolling view to the scroll view directly instead of assigning it to the table view's footer view, which means Infinite Scrolling should now work with UIScrollViews as well.
