### ISSUE TITLE
App crashes when adding the SVPullToRefresh view to UITableView

### ISSUE THREAD

**Issue by jimit** [samvermette/SVPullToRefresh#41]
I followed the required steps to add the SVPullToRefreshView but it doesn't seems to work. I get following error. 

-[UITableView addPullToRefreshWithActionHandler:]: unrecognized selector sent to instance 

Any idea? Thanks

**Comment by samvermette** [comment]
@jimit are you importing SVPullToRefresh.h? Are you getting a compiler warning about `addPullToRefreshWithActionHandler:` ? I'm pretty sure you must be missing something. Have a look at the demo project to see what you might be doing wrong.

**Comment by jimit** [comment]
I have checked everything. I don't get any warnings. The app runs just fine but as soon as I get to that view controller the app crashes and I get the error mentioned above.

**Comment by samvermette** [comment]
@jimit can you show me the code you're using to setup SVPullToRefresh?

**Comment by jimit** [comment]
#import "JCoffeeListViewController.h"
#import "SVPullToRefresh.h"

@interface JCoffeeListViewController ()

@synthesize tableView = _tableView;

@implementation JCoffeeListViewController
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  //Add the pull down to refresh view
  [self.tableView addPullToRefreshWithActionHandler:^{
       NSLog(@"It's working");  
  }];

}

**Comment by jimit** [comment]
Corrected**

#import "JCoffeeListViewController.h"
#import "SVPullToRefresh.h"

@interface JCoffeeListViewController ()

@implementation JCoffeeListViewController

@synthesize tableView = _tableView;

(void)viewDidLoad
{
[super viewDidLoad];

//Add the pull down to refresh view
[self.tableView addPullToRefreshWithActionHandler:^{
NSLog(@"It's working");

}];

}

**Comment by samvermette** [comment]
@jimit jeez I really have no idea, your code looks fine. I'm really puzzled... Which version of iOS are you running this on? And just to be sure, the demo project does work for you?

**Comment by jimit** [comment]
I had the same feeling. I can't seems to find why its behaving like this. 

I am running it on iOS 5.1.1 and the demo works for me. I will keep you posted as soon as I figure it out.

**Comment by yimingtang** [comment]
I've got the same problem. However, I remove the original source files of SVPullToRefresh. When I copy&paste, I selected the "add to target" option in Xcode. Finally, that's works fine.

**Comment by jimit** [comment]
@krafttuc Thanks for the tip. Somehow I had my unit test as the selected target. It works for me. 

@samvermette Thanks again.
