### ISSUE TITLE
disable infinite scroll indicator 

### ISSUE THREAD

**Issue by shoujs** [samvermette/SVPullToRefresh#44]
Is it possible to disable infinite scroll indicator if an exception occurs?

**Comment by samvermette** [comment]
@shoujs what do you mean an exception? If there's no more data to load for instance? Yes you can disable infinite scrolling by setting `tableView.showsInfiniteScrolling` to `NO`.

**Comment by shoujs** [comment]
I mean a network error. The indicator is still animating while a network error happens. Is there a way to stop animating?

**Comment by samvermette** [comment]
@shoujs ah, good call. I haven't planned for that. In the meantime you can probably make it stop by using the code I wrote in the previous comment. Will push a fix shortly that adds a stopAnimating method for the infinite scrolling.

**Comment by bosky101** [comment]
UPDATE:  just saw @samvermette answered this already above. Neat lib!

I am able to stop the infinity scrolling in the following manner

```
// reference code: SVViewController.m
- (void) viewDidLoad{ 
     // .... your regular code....

     // this was where you setup the call
     [self.tableView addInfiniteScrollingWithActionHandler:^{
          [self didAskToLoadMoreData];
     }];
 }

- (void) didAskToLoadMoreData{
    // simulate making a async request . once you have the data, call didLoadMoreData
    [self performSelector:@selector(didLoadMoreData) withObject:nil afterDelay:2];
}

 - (void) didLoadMoreData{
    tableView.showsInfiniteScrolling = NO;  // stops animating
    tableView.showsInfiniteScrolling = YES; // re-enables infinite scrolling
 }
```

~B

**Comment by samvermette** [comment]
Setting `showsInfiniteScrolling` to `NO` will now hide the activity indicator as well with my last commits. Sorry it took so long to fix.
