### ISSUE TITLE
Background color issue and arrow color not being set

### ISSUE THREAD

**Issue by thiagoperes** [samvermette/SVPullToRefresh#45]
Hi,

I wad fiddling with this component and I think I found something that you might wanna fix. Both are described in the screenshot below:

![issue](https://dl.dropbox.com/u/2259233/issue1.png)

1 - The background color and view does not have a flexible height, so when I apply a background color to it, I get this weird result
2 - The arrow color is not being set correctly

Here's a snippet of the code I'm using

```
// Pull to refresh setup
[NSDateFormatter setDefaultFormatterBehavior:NSDateFormatterBehaviorDefault];
NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
[dateFormatter setDateStyle:NSDateFormatterShortStyle];
[dateFormatter setTimeStyle:NSDateFormatterShortStyle];

self.tableView.pullToRefreshView.dateFormatter = dateFormatter;
[self.tableView.pullToRefreshView setTextColor:[UIColor whiteColor]];
[self.tableView.pullToRefreshView setArrowColor:[UIColor redColor]];
[self.tableView.pullToRefreshView setBackgroundColor:[UIColor blackColor]];
__block KPPackagesViewController *weakSelf = self;
[self.tableView addPullToRefreshWithActionHandler:^{
    [weakSelf reloadTableViewDataSource];
}];
// END: Pull to refresh setup
```

I tried cleaning the project, removing the app from simulator etc just to make sure but the problem persists.

Thanks

**Comment by samvermette** [comment]
@thiagoperes 1 is a known behavior, and I don't think the view should stretch depending on scroll view content offset. What you could do is add another UIView to the scroll view (give it a frame `CGRectMake(0, -400, 320, 400)` for instance) and set its background color. Make sure you add this view **before** you add the pull to refresh view.

A temporary workaround for 2 is to set `arrowColor` **after** calling `addPullToRefreshWithActionHandler:`. I will leave this issue open until I get this one fixed.

**Comment by samvermette** [comment]
The 2nd issue you reported should now be fixed with my latest push. Sorry it took so long.
