### ISSUE TITLE
Background color issue when view is created without width

### ISSUE THREAD

**Issue by oskargargas** [samvermette/SVPullToRefresh#46]
Hi,

I'm integrating SVPullToRefresh with my project and noticed that it's not working correctly with views created directly from code and not using Interface Builder.

SVPullToRefresh needs to use autoresizing masks to work correctly.
It was a quick fix by adding one line to initWithScrollView:

``` objc

- (id)initWithScrollView:(UIScrollView *)scrollView {
    self = [super initWithFrame:CGRectZero];
    self.scrollView = scrollView;

    // default styling values
    self.activityIndicatorViewStyle = UIActivityIndicatorViewStyleGray;
    self.textColor = [UIColor darkGrayColor];

    self.originalScrollViewContentInset = self.scrollView.contentInset;

    self.autoresizingMask = UIViewAutoresizingFlexibleWidth;

    return self;
}
```

**Comment by samvermette** [comment]
@oskargargas fixed with my last commit. Sorry it took so long and thanks!
