### ISSUE TITLE
The Label isn't centered to the view

### ISSUE THREAD

**Issue by freak4pc** [samvermette/SVPullToRefresh#48]
I'm using it on a UIWebView's ScrollView, and this is the result:

![](http://f.cl.ly/items/2G1z1t2d0e1C3g1g423P/Screen%20Shot%202012-08-14%20at%208.47.18%20PM.png)

**Comment by samvermette** [comment]
@freak4pc that is the intended behavior, so that when it's showing "Pull down to refresh" then the label is kind of centered.

**Comment by freak4pc** [comment]
Hey Sam, Thanks for replying !
Wouldn't it help to make the label width 100% of its parent UIView (320px usually) And use UITextAlignmentCenter?
That way you would only really have to take care of moving the ActivityIndicator.

Thanks again,
Shai

**Comment by samvermette** [comment]
Well the idea was to replicate the pull down to common pull down to refresh view out there. The label text is always aligned on the left, and personally I find it weird to have it horizontally centered. But then again, that's very personal. Feel free to fork SVPullToRefresh to have it be centered horizontally.
