### ISSUE TITLE
cause leaks test on iPad 5.1 simulator

### ISSUE THREAD

**Issue by kitsionchen** [samvermette/SVPullToRefresh#49]
Hi All, 
i test the SVPullToRefresh demo on iPad 5.1 simulator and use instruments to profile. when i drag up and down the table view, then found the leaks.

**Comment by kitsionchen** [comment]
btw, test on iPad 5.0 simulator is ok.

**Comment by samvermette** [comment]
Try again with the big refactor I just pushed and re-open this issue if you're still seeing leaks.
