### ISSUE TITLE
Using pull to refresh on horizontal tables.

### ISSUE THREAD

**Issue by navisingh** [samvermette/SVPullToRefresh#50]
I have had success using the SVPullToRefresh on UITables which are oriented vertically - the traditional way.  
I have a table that is rotated to display horizontally.  I tried using class for this horizontal table.  Unfortunately it crashes at:
- (void)setScrollViewContentInset:(UIEdgeInsets)contentInset {
  [UIView animateWithDuration:0.3 delay:0 options:UIViewAnimationOptionAllowUserInteraction|UIViewAnimationOptionBeginFromCurrentState animations:^{
      self.scrollView.contentInset = contentInset;
  } completion:^(BOOL finished) {
  ====>>>        if(self.state == SVPullToRefreshStateHidden && contentInset.top == self.originalScrollViewContentInset.top)
          [UIView animateWithDuration:0.2 delay:0 options:UIViewAnimationOptionAllowUserInteraction animations:^{
              arrow.alpha = 0;
          } completion:NULL];
  }];
  }

Any clues what I need to do to make this class work for horizontal tables as well?

**Comment by samvermette** [comment]
@navisingh SVPullToRefresh wasn't designed to work horizontally, and so I never tested it against that situation. My guess is that I think it would add a lot of complexity for a very small use case. Closing the issue for now, feel free to re-open it if you end up implementing this.
