### ISSUE TITLE
Empty table view loses cell separators with infinite scrolling

### ISSUE THREAD

**Issue by gstro** [samvermette/SVPullToRefresh#51]
Before adding `addInfiniteScrollingWithActionHandler:` an empty default table view (`numberOfRows` returning 0) will have blank cells marked with light grey separators. After adding the above method, an empty table view will appear more like a blank scroll view before cells are populated and added. Once cells are added, everything is great! Any suggestions?

**Comment by gstro** [comment]
"Fixed" by adding method `addInfiniteScrollingWithActionHandler:` after cells have been added (checking for the `showsInfiniteScrolling`). Leaving open in case you want to make any internal changes. Great code, thanks!

**Comment by samvermette** [comment]
The infinite scrolling view is now added to the scroll view directly instead of the table view's footer view. That should solve your issue. Let me know if it doesn't.
