### ISSUE TITLE
I want to remove infinite scrolling after there is no more content.

### ISSUE THREAD

**Issue by Jeswang** [samvermette/SVPullToRefresh#52]
I want to remove infinite scrolling after there is no more content. Current situation is when I set showsInfiniteScrolling = NO, it still take the space. Any idea?

**Comment by pcasaretto** [comment]
:+1: 
`tableView.showsInfiniteScrolling = NO;` is not removing the table cell, it is however not calling the callback.

**Comment by pcasaretto** [comment]
The latest release fixed this for me.

**Comment by Jeswang** [comment]
@pcasaretto  It seems I was confused by the cocoapods which will not update the lib automatic. With the latest code, problem solved.
