### ISSUE TITLE
InnifiteScrollingView

### ISSUE THREAD

**Issue by lts1610** [samvermette/SVPullToRefresh#54]
How to disable accelerate of scrollView when innifite?. It make my eye disorder. :)

And a bug: Activity indicator of scrollview not show.

Thanks for best project.

**Comment by samvermette** [comment]
@lts1610 not sure what you mean by "accelerate of scrollView when infinite". The bounce behavior?

Also, under which circumstances does the activity indicator not show up?

**Comment by lts1610** [comment]
---->The bounce behavior?
              Yes, I think so.
-->Also, under which circumstances does the activity indicator not show up?
              Sorry, I wrote wrong. ActivityIndicatorView of innifiteScrollView not show up. Somtimes, It appears.

**Comment by lts1610** [comment]
I perform my function (load more) delay affter 2s. And it works fine.

Thank @samvermette !

**Comment by samvermette** [comment]
@lts1610 the bounce behavior is something you can disable on the UITableView itself (property is `alwaysBounceVertically` I think. I'm not sure about the infinite scroll activity indicator disappearing, I will look into it.

**Comment by samvermette** [comment]
Try again with the refactor I just pushed and re-open the issue if the disappearing activity indicator still happens.
