### ISSUE TITLE
DataSource = 0

### ISSUE THREAD

**Issue by melzarei** [samvermette/SVPullToRefresh#55]
Hello,
I''m using GMGridView to display my data and added the PTR , it works good but if there is no internet connection and the number of cells = 0 it doesn't appear and no scroll is done , how can I get this fixed ?

**Comment by lts1610** [comment]
if (list.count == 0) tableview.pullToRefreshView.showsInfiniteScrolling == NO;

May this code helping to you.

**Comment by samvermette** [comment]
@melzarei this sounds like something you need to handle in your own code. SVPullToRefresh isn't aware of your data source. Thanks for chipping in @lts1610.
