### ISSUE TITLE
When a update is release, tag in Podspec should be updated.

### ISSUE THREAD

**Issue by jcoleman** [samvermette/SVPullToRefresh#61]
We now have tag 0.3 but the Podspec still refers to 0.2. I can open a pull request to fix the current copy if you'd like.

**Comment by jwilling** [comment]
The Podspec for 1.3 seems to be pointing to the 1.3 tag correctly. Am I missing something?

**Comment by jcoleman** [comment]
See https://github.com/samvermette/SVPullToRefresh/blob/0.3/SVPullToRefresh.podspec -- the source is configured to used 0.2. (This is also the case in master.)

**Comment by jwilling** [comment]
Ahh, I was looking at the CocoaPods' spec repo, which has the correct 0.3 version tag set up.

**Comment by jcoleman** [comment]
And certainly that's the most important one, I was just noting that the actual repo didn't.

**Comment by samvermette** [comment]
I'm still puzzled at what's the best way to work with CocoaPods. I used to have access to the official repo but ended up leaving the group because I kept getting an insane amount of notifications every day. Maybe that's fixed with GitHub's new notification system...

Is there a way I can have my podspec file to always point to the latest commit? Or at least make it so that every time I add a tag to my repository, it automatically update/push a podspec file that reflects this new version?

**Comment by jwilling** [comment]
Yes, the email spam has been resolved now. Unfortunately, there's no way to create an automatic podspec, but it's really easy to update a new one for each tag. If you specifically want the latest commit, there's always `:head`.

**Comment by samvermette** [comment]
@jwilling thanks. Where would I put `:head`? Like this?

```
s.source   = { :git => 'https://github.com/samvermette/SVPullToRefresh', :head }
```

**Comment by jwilling** [comment]
To tell you the truth, I've never used `:head` from within podspecs themselves, only through a Podfile. Might be better to get in touch with someone more knowledgeable than I about that.

Come to think of it, using `:head` might be unnecessary. If you leave out the specific version tag, and just provide the git repo I think it always uses the most recent version. I could be (and probably am) wrong about that, though.

**Comment by samvermette** [comment]
@jwilling okay will try that, thanks. Can you add me to the CocoaPodspecs group again please?

**Comment by jwilling** [comment]
@samvermette I'm a member there, but not an admin. Best get in contact with @alloy, @irrationalfab, or another admin to join again.

**Comment by jcoleman** [comment]
I think that (as I understand it) `:head` may be the way to go. The benefit to having the Podspec in the project repo itself (as opposed to merely in the cocoapods repo) is that then someone can easily specify that they'd like to use a specific tag, branch, or commit even if that tag/branch/commit doesn't (yet) have an official Podsepc in the cocoapods repo.

**Comment by fabiopelosin** [comment]
@samvermette I've added you to the group.

> Is there a way I can have my podspec file to always point to the latest commit? Or at least make it so that every time I add a tag to my repository, it automatically update/push a podspec file that reflects this new version?

You can do something like:

``` ruby
Pod::Spec.new do |s|
  s.name     = 'SVPullToRefresh'
  s.version  = '0.3'
  s.source   = { :git => 'https://github.com/samvermette/SVPullToRefresh.git',
                 :tag => "#{s.version}" }
  # [redacted]
end
```

Anyway at the end of the day for releasing a lib under CocoaPods one should still do those manual steps:
- git tag
- edit the podspec to indicate the new version
- `pod push master` (if you have push access)

However one day or the other I should do a companion command line tool for automating the management of pods with git.

> To tell you the truth, I've never used :head from within podspecs themselves, only through a Podfile. Might be better to get in touch with someone more knowledgeable than I about that.

@jwilling  You should never do this and there should never be the need to.

**Comment by jwilling** [comment]
@irrationalfab If I recall correctly that's what Eloy told me to do a couple months ago when I had the same question as @samvermette. Have things changed since then?

**Comment by fabiopelosin** [comment]
> @irrationalfab If I recall correctly that's what Eloy told me to do a couple months ago when I had the same question as @samvermette. Have things changed since then?

I doubt that @alloy told you so. I guess that he meant in a Podfile, but there was a misunderstanding. Anyway you should never use the head option to define the source of a podspec. Moreover if you want a head pointing podspec (for your usage) you can do:

``` ruby
s.source   = { :git => 'https://github.com/samvermette/SVPullToRefresh' }
```

Finally, now that I think about it:

``` ruby
s.source   = { :git => 'https://github.com/samvermette/SVPullToRefresh', :head }
```

Is not even valid ruby syntax and should crash (it is a hash key without a value).

**Comment by jwilling** [comment]
@irrationalfab Ahh, I thought you were referring to this:

> If you leave out the specific version tag, and just provide the git repo I think it always uses the most recent version.

**Comment by samvermette** [comment]
@irrationalfab @jwilling thanks for the help guys.

Another unanswered interrogation I have is: do I have to include the podspec file in my project repository as well? I understand that the one that matters is the one I push to CocoaPods/Specs, but I have seen many dev include it into their own project repo as well, yet I see no reason to since the tags are what link my project to the podspec... does that make sense?

**Comment by jcoleman** [comment]
@samvermette: As I mentioned earlier, the benefit to having the Podspec in the project repository itself (as opposed to merely in the cocoapods repo) is that then someone can easily specify that they'd like to use a specific tag, branch, or commit even if that tag/branch/commit doesn't (yet) have an official Podsepc in the cocoapods repo.

**Comment by fabiopelosin** [comment]
Another good reason are locally sourced pods.

Consider that while using a pod you find an enhancement that you want to perform. It is then possible to checkout a working copy of the library and change the dependency in the Podfile file to:

``` ruby
pod 'SVPullToRefresh', :local => '~/path/to/my/clone/SVPullToRefresh'
```

Using this option the Pods project links to the files contained in this folder so it is possible to perform source control and contribute back. This option requires a podspec in the root of the folder.

**Comment by jcoleman** [comment]
To add on to what @irrationalfab noted, it also helps if you fork the project. While developing changes to it, you need to be able to run your project against those files. And if the podspec is in the repo, then it's easy to just point the Podfile dependency at your fork while you develop the changes.

**Comment by samvermette** [comment]
Thanks all. I have a better understanding of how podspecs work now and will make sure to take better care of versioning controlling of my repos and their podspec.
