### ISSUE TITLE
willMoveToSuperview implementation prevents using UIScrollView as a root view in a navigation controller

### ISSUE THREAD

**Issue by rayh** [samvermette/SVPullToRefresh#62]
When the navigation controller pushes on a new controller, the previous view is removed from the hierarchy (but not released) and so willMoveToSuperview gets called.  This means that when the user returns to the view, the pullToRefresh instance is re-created and doesn't function as expected.

My understanding is that an associated object marked "retain" will be released along with the owning object.  If this is the case (and I could be mistaken), this pre-emptive removal of the views may be unnecessary.

I'm running this in iOS6 simulator in Xcode 4.5 GM

**Comment by yimingtang** [comment]
Yeah, I found the problem just now. I comment `willMoveToSuperview` method at present as a quick and dirty fix. I wonder how to solve such problem.

**Comment by samvermette** [comment]
Thanks guys. I'm currently working on a big refactor of how things are handled internally which will fix this issue once and for all. In it's current form, it seems that it is not possible to have the view probably get removed and/or dealloced when appropriate. Will report back shortly.

**Comment by mdestagnol** [comment]
Hello @samvermette, any news on this fix? And btw thanks for this great lib :)

**Comment by bassrock** [comment]
I two am encountering this issue. Any news and great implementation on this best I have seen!

**Comment by samvermette** [comment]
Sorry guys, been crazy busy with my app Transit. It might be a while before I'm able to wrap up this refactor. In the meantime, you can put the pull to refresh code in viewWillAppear and I believe that's a temporary workaround.

**Comment by bassrock** [comment]
No problem. With putting it in viewWillAppear I also added a check to see if the pull to refresh view is nil or its width = 0. Otherwise I found it gets added multiple times.

**Comment by samvermette** [comment]
Fixed in the refactor I just pushed. Sorry it took so long.
