### ISSUE TITLE
PullToRefresh disappears if the UITableViews owning it is not wrapped up in a UIView

### ISSUE THREAD

**Issue by nightbirdsevolve** [samvermette/SVPullToRefresh#63]
I have this case where i do not use any UIViewControllers subclasses but instead straight
UITableViewController subclasses sitting in a UINavigationController

so, the UITableView owning PullToRefresh is not sitting in a UIView.

now, when i transition from one controller to another using pushViewController, the pulltorefresh functionality vanishes.
I figured it was because of this :

```
@implementation UIScrollView (SVPullToRefresh)

  - (void)willMoveToSuperview:(UIView *)newSuperview
  { 
    if(!newSuperview)
    {
      [self.pullToRefreshView removeFromSuperview];
      self.pullToRefreshView = nil;

      [self.infiniteScrollingView removeFromSuperview];
      self.infiniteScrollingView = nil;
    }
  }
```

I'm no view hierarchy expert so, guess i'll stick with creating my UITableViews inside UIViewControllers as it works fine that way :D

**Comment by nightbirdsevolve** [comment]
seems like issue #62 is similar, sorry for the repost

**Comment by samvermette** [comment]
This is fixed with the big refactor I just pushed. Sorry it took so long.
