### ISSUE TITLE
InfiniteScrollingWithActionHandler triggered twice without waiting until the first one finishes

### ISSUE THREAD

**Issue by toyhunter** [samvermette/SVPullToRefresh#65]
```
__unsafe_unretained BrowseLookViewController *vc=self; 
[self.lookFeedView.mainTableView addInfiniteScrollingWithActionHandler:^{
    [vc loadLooksToFeedView];
}];
```

With the above code, I found some strange behavior of InfiniteScrolling.
While I am scrolling down to the bottom and still dragging more and more to the bottom, I found that loadLooksToFeedView was called twice in a row.
How can I ensure that this will be called only once and finishes before the next call begins. 

Does InfiniteScrolling already prevent this from occurring or have I done anything wrong?
Does it check progressIndicator status whether it is still animating before executing the action handler?

**Comment by samvermette** [comment]
I added additional checks in the refactor I just pushed. Feel free to re-open the issue if you're still seeing duplicate calls to the infinite scrolling action handler.
