### ISSUE TITLE
Consider hiding date label if showsPullToRefresh is NO

### ISSUE THREAD

**Issue by jsm174** [samvermette/SVPullToRefresh#68]
I wanted to hide SVPullToRefresh when the user is editing a table. I have mine set up to show a refresh date. The refresh date still is displayed when I use:

```
    tableView.showsPullToRefresh = NO
```

I'm not sure if that was the original intention but if not, I think it would be good to hide it.

For the time being, my work around is:

```
    tableView.showsPullToRefresh = !editing;
    tableView.pullToRefreshView.dateLabel.hidden = editing;
```

**Comment by samvermette** [comment]
Fixed in the refactor I just pushed. Setting `showsPullToRefresh` to `NO` will now hide all the labels by default.
