### ISSUE TITLE
ScrollView Horizontal Content Offset Overwritten

### ISSUE THREAD

**Issue by esetnik** [samvermette/SVPullToRefresh#77]
When SVPullToRefresh calls `- (void)startAnimating` the horizontal content offset of the underlying scroll view is reset to 0.

`[self.scrollView setContentOffset:CGPointMake(0, -self.frame.size.height) animated:NO];`

This caused my scrollView to lose its horizontal content offset.

I was able to resolve by using the scrollView's original contentOffset.x with the following adjustment

`[self.scrollView setContentOffset:CGPointMake(self.scrollView.contentOffset.x, -self.frame.size.height) animated:NO];`

**Comment by samvermette** [comment]
Fixed with my last commit. Thanks!
