### ISSUE TITLE
Just wondering why last refreshed date is not shown?

### ISSUE THREAD

**Issue by kevinNgws** [samvermette/SVPullToRefresh#78]
In init frame, i set self.showsDateLabel = YES; but it not working correctly. Please advise. Thank you!

**Comment by kevinNgws** [comment]
Hi, I added 
- (NSString *)getLastUpdatedDate:(NSDate *)newLastUpdatedDate {
  NSDateFormatter *formatter;
  NSString *dateString;
  
  formatter = [[NSDateFormatter alloc] init];
  [formatter setDateFormat:@"dd-MM-yyyy HH:mm"];
  
  dateString = [formatter stringFromDate:[NSDate date]];
  
  return [NSString stringWithFormat:@"Last Updated: %@", dateString];
  }

and at - (void)layoutSubviews

if(hasCustomView) {
        ......
    }
    else {
        self.titleLabel.text = [self.titles objectAtIndex:self.state];

```
    NSString *subtitle = [self getLastUpdatedDate:[NSDate date]];
```

}

Hope this helps anyone who wanted an updated date as subtitle

**Comment by samvermette** [comment]
@kevinNgws please read the documentation. All the date stuff is now deprecated. You're now responsible of generating your own string using your own NSDateFormatter. The correct way to set a subtitle on SVPullToRefresh is now using the method `setSubtitle:forState:`.
