### ISSUE TITLE
Minor bug with removing non-existing observers

### ISSUE THREAD

**Issue by myster-t** [samvermette/SVPullToRefresh#79]
Hi Sam, thanks for your awesome library.  I found a bug in your new version, but it has a simple fix.  

In `- (void)setShowsPullToRefresh:`, it keys entirely off of the passed in BOOL for whether or not to add/remove observers.  This could be a problem if I accidentally call `self.scrollview.showsPullToRefresh = NO` twice in a row (or if I call it before adding an action handler). 

There probably is a cleaner way to do this, but I modified your code in two places:

1) I set `self.pullToRefreshView.hidden = YES` right after its created; and,
2) I modified your code to first check `if (self.pullToRefreshView && self.pullToRefreshView.hidden != !showsPullToRefresh)` before adding/removing observers (it's written in this funky way just to make it more readable as it mimics your code a line later... but this is probably only necessary because I don't know your code as well :P)

I did the same thing for infinite scrolling.

**Comment by samvermette** [comment]
This gets fixed with the pull request I just merged. Thanks!
