### ISSUE TITLE
Setting textColor property creates label placement problem

### ISSUE THREAD

**Issue by sarperdag** [samvermette/SVPullToRefresh#8]
if I am not using any lastupdatedate and setting the textColor property, there is a misplacement of the titleLabel. Commenting out dateLabel as below fixed the problem but there should be a better solution. 
- (void)setTextColor:(UIColor *)newTextColor {
  self.titleLabel.textColor = newTextColor;
  //self.dateLabel.textColor = newTextColor;
  }

**Comment by samvermette** [comment]
Thanks, fixed with my last commit.
