### ISSUE TITLE
Issues with scrollView that have predefined contentOffset.y's

### ISSUE THREAD

**Issue by myster-t** [samvermette/SVPullToRefresh#80]
I was having some problems using the new version with my UIScrollView that has a non-zero contentOffset.y and contentInset.top in some situations.  For instance, if you scroll up on this view, it also pushes a menu that sits at the very top of the view up and out of the window (while reducing the inset.top and increase the offset.y).

I solved this problem by creating a new property:
`@property (nonatomic, readwrite) CGFloat originalYOffset;`

And setting it inside of `- (void)addPullToRefreshWithActionHandler:`:
`view.originalYOffset = self.contentOffset.y;`

And now my `- (void)startAnimating` and `- (void)stopAnimating` functions look like:

```
- (void)startAnimating{
    if(self.scrollView.contentOffset.y >= self.originalYOffset) {
        [self.scrollView setContentOffset:CGPointMake(self.scrollView.contentOffset.x, self.originalYOffset - self.frame.size.height) animated:YES];
        self.wasTriggeredByUser = NO;
    }
    else
        self.wasTriggeredByUser = YES;

    self.state = SVPullToRefreshStateLoading;
}

- (void)stopAnimating {
    if (self.state != SVPullToRefreshStateStopped)
    {
        self.state = SVPullToRefreshStateStopped;

        if(!self.wasTriggeredByUser)
            [self.scrollView setContentOffset:CGPointMake(self.scrollView.contentOffset.x, self.originalYOffset) animated:YES];
    }
}
```

Two small things to note:
1. The check at the top of `- (void)startAnimating` only checked if the current offset.y is equal to 0, but should evaluate to true as long as it's not the user pulling it past the "natural" zero-th position of the scrollView.  An alternative to what I did is:
`if(self.scrollView.contentOffset.y >= -self.originalTopInset)`
2. I added a check inside of `- (void)stopAnimating` to see if the the animation needs to be stopped. This avoids the problem where the content offset start popping back to the top if `- (void)stopAnimating` gets called conservatively by the scrollView right before it gets dismissed

**Comment by xuyunan** [comment]
when i refresh data and call reloaddata method, the tableView scroll to top every time. something wrong in it i think.
any other people have this problem?

**Comment by xuyunan** [comment]
@phaitour you are right,haha.

**Comment by samvermette** [comment]
@phaitour could you submit this code change as a pull request? That would help a ton.

**Comment by pilot34** [comment]
I submitted pull request for related problem https://github.com/samvermette/SVPullToRefresh/pull/99
