### ISSUE TITLE
Expose titleLabel and subtitleLabel

### ISSUE THREAD

**Issue by yimingtang** [samvermette/SVPullToRefresh#83]
Hey Sam, I am wondering if it is a good idea that we expose the `titleLabel` and `subtileLabel` properties in `SVPullToRefreshView`.

I'd like to do some custom configurations on such kinds of labels, but I don't want to modify code in your library. You know, I may use pull-to-refresh in many situations and they look little different.

**Comment by samvermette** [comment]
Yeah I think this is a good idea. Can you submit a pull request? Make sure they're exposed as `readonly` attributes though.
