### ISSUE TITLE
iOS 4.3 compatibility

### ISSUE THREAD

**Issue by Lintom** [samvermette/SVPullToRefresh#87]
If i use this library in iOS 4.3, Xcode says : "The current deployment target does not support automated __weak references". Can i replace @property (nonatomic, weak) UIScrollView *scrollView to
@property (nonatomic, unsafe_unretained) UIScrollView *scrollView ? Project don't use ARC.

**Comment by samvermette** [comment]
Sorry for the late reply. I'm not sure what's the best way to go around this. I would have thought replacing `weak` with `assign`. Either way, I think you should target iOS 5+, nobody's using iOS 4 anymore.
