### ISSUE TITLE
doesn't work with section header (title/view), related to Issue #29

### ISSUE THREAD

**Issue by chrischenyc** [samvermette/SVPullToRefresh#90]
hi there,

it appears to me that Issue #29 still persists in the latest code. just add following in the Demo/SVViewController.m

(NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return @"Section Header"; }

I commented in the original #29 as well.

**Comment by yimingtang** [comment]
I also found this bug. Do you have any idea about it?

**Comment by chrischenyc** [comment]
okay, I forked this repo and fixed the issue: https://github.com/chenyuan/SVPullToRefresh

**Comment by yimingtang** [comment]
@chenyuan Great! Thank you! Can you send a pull request to upstream?

**Comment by chrischenyc** [comment]
pull request sent
