### ISSUE TITLE
CustomView x position

### ISSUE THREAD

**Issue by raphaeloliveira** [samvermette/SVPullToRefresh#98]
Hi Sam, I could not figure out why the self.bounds.size.width is 640 in the layoutSubviews method making my custom view x position 160 (my custom view width is 320).

CGPoint origin = CGPointMake(round((self.bounds.size.width-viewBounds.size.width)/2), round((self.bounds.size.height-viewBounds.size.height)/2));

I hardcoded 0 to solve the problem but I don't know why this is happening. At any moment I changed the UITableView frame nor the CustomView frame.
CGPoint origin = CGPointMake(0, round((self.bounds.size.height-viewBounds.size.height)/2));

**Comment by samvermette** [comment]
Maybe there's something wrong with your autoresizing masks? Even if you're confident you didn't change their frame I would have a look at your table view frame in viewDidLoad, viewWillAppear, etc.

**Comment by samvermette** [comment]
I just pushed some code that handles the horizontal centering differently. Can you check if you're still getting the issue with what's on HEAD?
